version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_file_storage
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    environment:
      - JAVA_OPTS=-Xmx512m
